services:
  - type: web
    name: adres-fur
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADRES_DATA_DIR
        value: /var/data
    disk:
      name: adres-data
      mountPath: /var/data
      sizeGB: 1
